spring:
  application:
    name: auction
  jpa:
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
---
spring:
  profiles:
    active: local
---
spring:
  profiles:
    active: prod