spring:
  application:
    name: aws_test
  jpa:
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info

metrics:
  export:
    prometheus:
      enabled: true

---
spring:
  profiles:
    active: local