name: Java CI with Gradle

# main 브랜치에 push, pr 이벤트시 동작합니다.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout 
      uses: actions/checkout@v4

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    # Spring Boot app Build
    - name: Spring Boot build
      run: ./gradlew clean build --exclude-task test
      
    # Docker Image Build
    - name: docker image build
      run: docker build -t ${{secrets.DOCKERHUB_USERNAME}}/aws-test .

    # DockerHub Login
    - name: docker login
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}

    # DockerHub push
    - name: docker Hub push
      run: docker push ${{secrets.DOCKERHUB_USERNAME}}/aws-test

    # GET GitHub IP
    - name: get GitHub IP 
      id: ip
      uses: haythem/public-ip@v1.2
      
# Configure AWS Credentials (6) - AWS 접근 권한 취득(IAM)
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

# Add github ip to AWS (7)
    - name: Add GitHub IP to AWS
      run: |
        aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32

# AWS EC2 Server Connect & Docker 명령어 실행 (8)
    - name: AWS EC2 Connection
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{secrets.SSH_PEM_KEY}} 
        port: ${{ secrets.EC2_SSH_PORT }}
        timeout: 60s
        script: |
          docker pull friedsaewoo/aws-test:latest
          sudo docker stop aws-test-ci || true
          sudo docker rm aws-test-ci || true
          sudo docker run -d -p 8080:8080 --name aws-test-ci --env-file /home/ubuntu/.env friedsaewoo/aws-test:latest

    # REMOVE Github IP FROM security group (9)
    - name: Remove IP FROM security group
      run: |
        aws ec2 revoke-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32













      
