name: Java CI with Gradle

# main 브랜치에 push, pr 이벤트시 동작합니다.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout 
      uses: actions/checkout@v4
      
    # Spring Boot app Build
    - name: Spring Boot build
      run: ./gradlew clean build --exclude-task test
      
    # Docker Image Build
    - name: docker image build
      run: docker build -t ${{secrets.DOCKERHUB_USERNAME}}/aws-test .

    # DockerHub Login
    - name: docker login
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PASSWORD}}

    # DockerHub push
    - name: docker Hub push
      run: docker push ${{secrets.DOCKERHUB_USERNAME}}/aws-test
